//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderMerge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderMerge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in method BtnMergeClick in MainWindow.
        /// </summary>
        internal static string ErrorBtnMergeClick {
            get {
                return ResourceManager.GetString("ErrorBtnMergeClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder1 and folder2 can&apos;t be the same, nothing to merge.
        /// </summary>
        internal static string ErrorEqualSourceFolders {
            get {
                return ResourceManager.GetString("ErrorEqualSourceFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in GetFilesRecursive.
        /// </summary>
        internal static string ErrorGetFilesRecursive {
            get {
                return ResourceManager.GetString("ErrorGetFilesRecursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error dynamically loading dll: .
        /// </summary>
        internal static string ErrorLoadingDll {
            get {
                return ResourceManager.GetString("ErrorLoadingDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging into the same folder not supported yet..
        /// </summary>
        internal static string ErrorMergeSourceFolderNotSupported {
            get {
                return ResourceManager.GetString("ErrorMergeSourceFolderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder1 couldn&apos;t be found.
        /// </summary>
        internal static string ErrorSourceFolder1NotExisiting {
            get {
                return ResourceManager.GetString("ErrorSourceFolder1NotExisiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder2 couldn&apos;t be found.
        /// </summary>
        internal static string ErrorSourceFolder2NotExisiting {
            get {
                return ResourceManager.GetString("ErrorSourceFolder2NotExisiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderCombo couldn&apos;t be found.
        /// </summary>
        internal static string ErrorSourceFolderComboNotExisiting {
            get {
                return ResourceManager.GetString("ErrorSourceFolderComboNotExisiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found.
        /// </summary>
        internal static string FilesFound {
            get {
                return ResourceManager.GetString("FilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished merging {0} files..
        /// </summary>
        internal static string FinishedMerging {
            get {
                return ResourceManager.GetString("FinishedMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging files.
        /// </summary>
        internal static string MergingFiles {
            get {
                return ResourceManager.GetString("MergingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder.
        /// </summary>
        internal static string PleaseSelectAFolder {
            get {
                return ResourceManager.GetString("PleaseSelectAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to merge into sourcefolder 1?.
        /// </summary>
        internal static string WarningMergeIntoFolder1 {
            get {
                return ResourceManager.GetString("WarningMergeIntoFolder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to merge into sourcefolder 2?.
        /// </summary>
        internal static string WarningMergeIntoFolder2 {
            get {
                return ResourceManager.GetString("WarningMergeIntoFolder2", resourceCulture);
            }
        }
    }
}
